version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db